apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-productservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-productservice
  template:
    metadata:
      labels:
        app: eshop-productservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: eshop-productservice
        image: gcr.io/architect-certification-289902/24/eshop-productservice@sha256:4c9d8a0e974223381e18e3b66d46364fd0b184c342f38bc96a18fc82a03ef5b9
        ports:
        - containerPort: 8092
        env:
        - name: PORT
          value: "8092"
        - name: MONGO_URI
          value: "mongodb://mongodb-arbiter-headless.default.svc.cluster.local/?replicaSet=rs0"
        - name: INIT_DATA
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-productservice
spec:
  type: ClusterIP
  selector:
    app: eshop-productservice
  ports:
  - name: api
    port: 8092
    targetPort: 8092